package br.com.contmatic.constantes.easyrandom;

public enum TipoDadoParaTesteFuncionario {
	VALIDO,
	NOME_NULL,
	NOME_EMPTY,
	NOME_BLANK_SPACE,
	NOME_INVALID_SIZE,
	EMAIL_NULL,
	EMAIL_BLANK_SPACE,
	EMAIL_EMPTY,
	EMAIL_INVALID_SIZE,
	EMAIL_WITH_SPECIAL_CARACTER,
	EMAIL_WITH_BLANK_SPACE,
	EMAIL_WITHOU_ARROBA,
	EMAIL_WITHOUT_DOT,
	CPF_NULL,
	CPF_EMPTY,
	CPF_BLANK_SPACE,
	CPF_WITH_SPECIAL_CARACTER,
	DATA_NASCIMENTO_NULL,
	CARGO_NULL,
	ENDERECO_NULL,
	TIPO_CONTRATO_NULL,
	SALARIO_NULL,
	SALARIO_PRECIA_SER_VALOR_MAIOR;
}
