package br.com.contmatic.constantes.easyrandom;

public enum TipoDadoParaTesteEmpresa {
	VALIDO,
	NOME_NULL,
	NOME_EMPTY,
	NOME_BLANK_SPACE,
	NOME_INVALID_SIZE,
	NOME__WITH_SPECIAL_CARACTER,
	EMAIL_NULL,
	EMAIL_BLANK_SPACE,
	EMAIL_EMPTY,
	EMAIL_INVALID_SIZE,
	EMAIL_WITH_SPECIAL_CARACTER,
	CNPJ_NULL,
	CNPJ_EMPTY,
	CNPJ_BLANK_SPACE,
	CNPJ_WITH_SPECIAL_CARACTER,
}
