package br.com.contmatic.easyrandom;

public enum TipoDadoParaTesteProduto {
	VALIDO,
	NOME_NULL,
	NOME_EMPTY,
	NOME_BLANK_SPACE,
	NOME_INVALID_SIZE,
	NOME__WITH_SPECIAL_CARACTER,
	PRECO_NULL,
	PRECO_INVALIDO,
	ESTOQUE_NULL,
	ESTOQUE_INVALIDO;
}
