package br.com.contmatic.easyrandom;

public enum TipoDadoParaTesteEndereco {
	VALIDO,
	CIDADE_NULL,
	CIDADE_EMPTY,
	CIDADE_CONTAINS_NUMBER,
	CIDADE_LESS_3_CARACTER,
	CIDADE_GREATER_50_CARACTER,
	CIDADE_WITH_SPECIAL_CARACTER,
	ESTADO_NULL,
	NUMERO_RESIDENCIA_LESS_THAN_ZERO,
	RUA_NULL,
	RUA_EMPTY,
	RUA_LESS_3_CARACTER,
	RUA_GREATER_50_CARACTER,
	RUA_WITH_SPECIAL_CARACTER,
	CEP_NULL,
	CEP_EMPTY,
	CEP_CONTAINS_WORD,
	CEP_LENGTH_DIFFERENCE_8,
	BAIRRO_NULL,
	BAIRRO_EMPTY,
	BAIRRO_CONTAINS_NUMBER,
	BAIRRO_LESS_3_CARACTER,
	BAIRRO_GREATER_50_CARACTER,
	BAIRRO_WITH_SPECIAL_CARACTER;
}
