package br.com.contmatic.easyrandom;

public enum TipoDadoParaTesteCliente {
	VALIDO,
	NOME_NULL,
	NOME_EMPTY,
	NOME_BLANK_SPACE,
	NOME_INVALID_SIZE,
	NOME__WITH_SPECIAL_CARACTER,
	EMAIL_NULL,
	EMAIL_BLANK_SPACE,
	EMAIL_EMPTY,
	EMAIL_INVALID_SIZE,
	EMAIL_WITH_SPECIAL_CARACTER,
	CPF_NULL,
	CPF_EMPTY,
	CPF_BLANK_SPACE,
	CPF_WITH_SPECIAL_CARACTER,
	DATA_NASCIMENTO_NULL,
	ENDERECO_NULL,
	DINHEIRO_CARTEIRA_NULL,
	DINHEIRO_CARTEIRA_PRECIA_SER_VALOR_MAIOR;
}
