package br.com.contmatic.easyrandom.enums;

public enum TipoDadoParaTesteEmpresa {
	VALIDO,
	NOME_NULL,
	NOME_EMPTY,
	NOME_BLANK_SPACE,
	NOME_INVALID_SIZE,
	NOME__WITH_SPECIAL_CARACTER,
	EMAIL_NULL,
	EMAIL_WITH_SPECIAL_CARACTER,
	EMAIL_WITH_BLANK_SPACE,
	EMAIL_WITH_NUMBER_AFTER_ARROBA,
	EMAIL_WITHOU_ARROBA,
	EMAIL_WITHOUT_DOT,
	EMAIL_BLANK_SPACE,
	EMAIL_EMPTY,
	EMAIL_INVALID_SIZE,
	CNPJ_NULL,
	CNPJ_EMPTY,
	CNPJ_BLANK_SPACE,
	CNPJ_WITH_SPECIAL_CARACTER,
}
